import Mathlib.NumberTheory.LSeries.RiemannZeta

/-!
# Lemma Ladder: RH implies ζ non-vanishing on Re(s) = 1
Generated by: Project HYPERZETA Lemma Ladder
Difficulty: medium
Timestamp: 2026-03-27T20:48:11.670942
-/

open Complex in
theorem rh_implies_nonvanishing (h_rh : RiemannHypothesis) (s : ℂ)
    (h_re : s.re = 1) (h_ne : s ≠ 1) :
    riemannZeta s ≠ 0 :=
  by
  intro h_zero
  have h_not_trivial : ¬∃ (n : ℕ), s = -2 * (↑n + 1) := by
    rintro ⟨n, hn⟩
    rw [hn] at h_re
    simp at h_re
    linarith
  have h_half := h_rh s h_zero h_not_trivial h_ne
  linarith
