import Mathlib.NumberTheory.LSeries.RiemannZeta

/-!
# Lemma Ladder: Trivial zeros: ζ(-2(n+1)) = 0
Generated by: Project HYPERZETA Lemma Ladder
Difficulty: trivial
Timestamp: 2026-03-27T08:57:59.967452
-/

theorem zeta_trivial_zeros (n : ℕ) : riemannZeta (-2 * (↑n + 1)) = 0 :=
  by exact riemannZeta_neg_two_mul_nat_add_one n
