import Mathlib.NumberTheory.LSeries.RiemannZeta

/-!
# Lemma Ladder: Mertens trigonometric inequality: 3 + 4cos(θ) + cos(2θ) ≥ 0
Generated by: Project HYPERZETA Lemma Ladder
Difficulty: easy
Timestamp: 2026-03-27T20:46:40.113170
-/

theorem mertens_trig (θ : ℝ) :
    0 ≤ 3 + 4 * Real.cos θ + Real.cos (2 * θ) :=
  by
  rw [Real.cos_two_mul]
  nlinarith [sq_nonneg (1 + Real.cos θ)]
