import Mathlib.NumberTheory.LSeries.RiemannZeta

/-!
# Lemma Ladder: ζ(0) = -1/2
Generated by: Project HYPERZETA Lemma Ladder
Difficulty: trivial
Timestamp: 2026-03-27T08:57:33.867581
-/

theorem zeta_at_zero : riemannZeta 0 = -1/2 :=
  by simp [riemannZeta_zero]
