import Mathlib.NumberTheory.LSeries.RiemannZeta

/-!
# Lemma Ladder: ζ(s) is differentiable for s ≠ 1
Generated by: Project HYPERZETA Lemma Ladder
Difficulty: easy-medium
Timestamp: 2026-03-27T09:02:00.619347
-/

theorem zeta_differentiable (s : ℂ) (hs : s ≠ 1) :
    DifferentiableAt ℂ riemannZeta s :=
  by exact differentiableAt_riemannZeta hs
