import Mathlib.NumberTheory.LSeries.RiemannZeta

/-!
# Lemma Ladder: Functional equation: Λ(1-s) = Λ(s)
Generated by: Project HYPERZETA Lemma Ladder
Difficulty: easy
Timestamp: 2026-03-27T08:59:05.659825
-/

theorem completed_zeta_symmetry (s : ℂ) :
    completedRiemannZeta (1 - s) = completedRiemannZeta s :=
  by exact completedRiemannZeta_one_sub s
