import Mathlib.NumberTheory.LSeries.RiemannZeta

/-!
# Lemma Ladder: Λ₀(s) is entire (differentiable everywhere)
Generated by: Project HYPERZETA Lemma Ladder
Difficulty: easy-medium
Timestamp: 2026-03-27T09:03:30.860273
-/

theorem completed_zeta0_entire :
    Differentiable ℂ completedRiemannZeta₀ :=
  by exact differentiable_completedZeta₀
