import Mathlib.NumberTheory.LSeries.RiemannZeta

/-!
# Lemma Ladder: Non-trivial zeros are symmetric: ζ(s)=0 → ζ(1-s)=0
Generated by: Project HYPERZETA Lemma Ladder
Difficulty: medium
Timestamp: 2026-03-27T19:14:33.293780
-/

theorem zero_symmetry (s : ℂ)
    (h_zero : riemannZeta s = 0)
    (h_not_neg_nat : ∀ n : ℕ, s ≠ -↑n)
    (h_ne_one : s ≠ 1) :
    riemannZeta (1 - s) = 0 :=
  by rw [riemannZeta_one_sub h_not_neg_nat h_ne_one, h_zero, mul_zero]
