import Mathlib.NumberTheory.LSeries.RiemannZeta

/-!
# Lemma Ladder: Entire functional equation: Λ₀(1-s) = Λ₀(s)
Generated by: Project HYPERZETA Lemma Ladder
Difficulty: easy
Timestamp: 2026-03-27T09:00:39.138370
-/

theorem completed_zeta0_symmetry (s : ℂ) :
    completedRiemannZeta₀ (1 - s) = completedRiemannZeta₀ s :=
  by exact completedRiemannZeta₀_one_sub s
