import os
import uuid
import json
import math
import re
import urllib.request
import urllib.error
import subprocess
from datetime import datetime

# Mathlib API surface for the Riemann Hypothesis — fed to the LLM as toolkit hints
MATHLIB_RH_TOOLKIT = """
Available Mathlib4 lemmas and definitions for the Riemann Hypothesis:

CORE DEFINITIONS:
- `riemannZeta : ℂ → ℂ` — The Riemann zeta function ζ(s).
- `RiemannHypothesis : Prop` — The official Millennium Prize statement.
- `completedRiemannZeta : ℂ → ℂ` — The completed zeta Λ(s) = π^(-s/2) Γ(s/2) ζ(s).
- `completedRiemannZeta₀ : ℂ → ℂ` — Λ(s) with poles removed (entire function).

KEY LEMMAS:
- `riemannZeta_one_sub` — Functional equation: ζ(1-s) = 2^(1-s) * π^(-s) * Γ(s) * sin(π(1-s)/2) * ζ(s)
- `completedRiemannZeta_one_sub` — Symmetry: Λ(1-s) = Λ(s) for all s.
- `completedRiemannZeta₀_one_sub` — Symmetry for the entire version: Λ₀(1-s) = Λ₀(s).
- `differentiableAt_riemannZeta` — ζ(s) is differentiable away from s = 1.
- `differentiable_completedZeta₀` — Λ₀(s) is entire (differentiable everywhere).
- `riemannZeta_neg_two_mul_nat_add_one` — Trivial zeros: ζ(-2(n+1)) = 0.
- `riemannZeta_zero` — ζ(0) = -1/2.
- `riemannZeta_def_of_ne_zero` — For s ≠ 0: ζ(s) = Λ(s) / Γℝ(s).
- `zeta_eq_tsum_one_div_nat_cpow` — For Re(s) > 1: ζ(s) = ∑ 1/n^s.
- `completedRiemannZeta_residue_one` — The residue of Λ at s=1 is 1.

USEFUL TACTICS: `intro`, `obtain`, `rcases`, `exact`, `apply`, `have`, `simp`, `norm_num`,
  `linarith`, `omega`, `ring`, `field_simp`, `push_neg`, `by_contra`, `contradiction`,
  `refine`, `use`, `constructor`, `specialize`, `rw`, `conv`, `calc`
""".strip()


class Lean4Exporter:
    """
    Bridges the Floating-Point mathematics engine to the Symbolic Theorem framework.
    Translates stable topological bounds into raw .lean files and orchestrates LLM tactic solving.
    """
    def __init__(self, proofs_dir: str = "../proofs", model: str = "qwen2.5-coder:32b"):
        self.proofs_dir = os.path.abspath(proofs_dir)
        self.model = model
        os.makedirs(self.proofs_dir, exist_ok=True)

    def generate_betti_theorem(self, betti_score: float, hyper_tensor: list[float]) -> str:
        proof_id = str(uuid.uuid4())[:8]
        timestamp = datetime.utcnow().isoformat()
        
        file_name = f"StableTopology_{proof_id}.lean"
        file_path = os.path.join(self.proofs_dir, file_name)
        
        # Use ONLY the targeted import — not the full 3GB Mathlib monolith
        # This module transitively pulls in Complex, Gamma, HurwitzZeta, and all
        # definitions needed for the RiemannHypothesis Prop
        #
        # IMPORTANT: The template uses `sorry` as a TERM-MODE placeholder (no `by`).
        # The LLM is instructed to output `by\n  <tactics>`, which replaces `sorry`
        # cleanly without producing a double-`by` syntax error.
        lean_template = f"""import Mathlib.NumberTheory.LSeries.RiemannZeta

/-!
# Millennium Prize: The Riemann Hypothesis
Generated by: Project HYPERZETA Headless Recursion Node
Timestamp: {timestamp}
16D Sedenion Cross-Product Metric: {betti_score:.4f}

Targeting Mathlib's official `RiemannHypothesis` Prop.
A proof of this type is worth $1,000,000.
-/

/--
  The Riemann Hypothesis as stated by Mathlib4:
  ∀ (s : ℂ), riemannZeta s = 0 →
    (¬∃ (n : ℕ), s = -2 * (↑n + 1)) →  -- not a trivial zero
    s ≠ 1 →                              -- not the pole
    s.re = 1 / 2
-/
theorem hyperzeta_rh : RiemannHypothesis :=
  sorry
"""
        with open(file_path, "w") as f:
            f.write(lean_template)
            
        return file_path

    def _compute_temperature(self, attempt: int) -> float:
        """
        Cyclic cosine annealing: temperature oscillates smoothly between
        0.3 (precise logical reasoning) and 1.0 (creative exploration)
        in waves of 50 iterations. This prevents the model from getting
        stuck at either extreme for the entire 40,000 iteration run.
        """
        cycle_length = 50
        phase = (attempt % cycle_length) / cycle_length
        return 0.3 + 0.7 * (1 - math.cos(math.pi * phase)) / 2

    def _sanitize_llm_output(self, raw_output: str) -> str:
        """
        Cleans LLM output to produce a valid Lean 4 tactic block.
        Handles: markdown fences, stray prose, double-by prevention.
        """
        output = raw_output.strip()
        
        # Strip markdown fences
        output = output.replace("```lean4", "").replace("```lean", "").replace("```", "").strip()
        
        # Strip any leading prose before the actual tactic block
        # Look for the first line that starts with `by` or a known tactic
        lines = output.split("\n")
        start_idx = 0
        for i, line in enumerate(lines):
            stripped = line.strip()
            if stripped.startswith("by") or stripped.startswith("intro") or \
               stripped.startswith("unfold") or stripped.startswith("simp") or \
               stripped.startswith("apply") or stripped.startswith("have") or \
               stripped.startswith("exact") or stripped.startswith("obtain") or \
               stripped.startswith("rcases") or stripped.startswith("push_neg") or \
               stripped.startswith("by_contra"):
                start_idx = i
                break
        output = "\n".join(lines[start_idx:]).strip()
        
        # Ensure the output starts with `by` for tactic mode
        # (the template uses term-mode `sorry` so the LLM needs to provide `by`)
        if not output.startswith("by"):
            output = "by\n  " + output
        
        return output

    def expand_proof(self, file_path: str, pristine_template: str, 
                     previous_error: str = None, attempt: int = 0,
                     failed_history: list = None) -> str:
        """
        Connects natively via built-in URLlib to local Ollama.
        Uses cyclic temperature annealing, failed tactic history,
        and Mathlib API hints to maximize proof search quality.
        """
        if not os.path.exists(file_path):
            return "System File missing."
            
        system_prompt = f"""You are a world-class Lean 4 theorem prover with deep expertise in Mathlib4.
Your goal is to prove the Riemann Hypothesis by replacing the `sorry` in the theorem below.
Output ONLY the exact tactic block that replaces `sorry`. No markdown, no explanations, no file rewrites.

CRITICAL: Your output must be a valid Lean 4 tactic proof starting with `by`.
The `sorry` in the template is in TERM position, so you must provide `by` followed by tactics.
Example format:
by
  intro s h_zero h_not_trivial h_ne_one
  <your proof tactics here>

This is attempt #{attempt + 1}. Try a genuinely novel approach.

THE THEOREM TO PROVE:
```lean
{pristine_template}
```

{MATHLIB_RH_TOOLKIT}
"""
        if previous_error:
            system_prompt += f"\n\nYour PREVIOUS attempt FAILED with this Lean 4 compiler error:\n{previous_error}\n\nAnalyze the error carefully. Try a COMPLETELY DIFFERENT approach."
        
        # Inject rolling history of failed attempts to prevent cycling
        if failed_history and len(failed_history) > 0:
            history_block = "\n".join([f"  - {h[:150]}" for h in failed_history[-3:]])
            system_prompt += f"\n\nPREVIOUSLY FAILED APPROACHES (DO NOT REPEAT):\n{history_block}"

        # Cyclic cosine temperature annealing
        temp = self._compute_temperature(attempt)

        try:
            req_body = json.dumps({
                "model": self.model,
                "prompt": system_prompt,
                "stream": False,
                "options": {
                    "temperature": temp,
                    "num_ctx": 4096,        # Generous window — we have 96GB unified memory
                    "num_thread": 8,        # Apple Silicon Performance Cores
                    "num_gpu": 99,          # Force all layers into Unified Memory (Metal)
                    "repeat_penalty": 1.1,  # Penalize repetitive token sequences
                    "top_p": 0.95           # Nucleus sampling for diverse tactic exploration
                }
            }).encode("utf-8")
            
            req = urllib.request.Request(
                "http://127.0.0.1:11434/api/generate",
                data=req_body,
                headers={"Content-Type": "application/json"}
            )
            
            with urllib.request.urlopen(req) as response:
                response_data = json.loads(response.read().decode("utf-8"))
                llm_output = response_data.get("response", "")
                
                # Sanitize and structure the LLM output
                clean_tactics = self._sanitize_llm_output(llm_output)
                
                # Inject AI tactic into pristine theorem, replacing sorry
                injected_mathematics = pristine_template.replace("sorry", clean_tactics)
                
                with open(file_path, "w") as f:
                    f.write(injected_mathematics)
                    
                return "Mac Local Ollama Inference Array Expanded."
                
        except urllib.error.URLError:
            return "Ollama Server Not Running locally natively spanning port 11434."

    def verify_proof(self, file_path: str) -> dict:
        """
        Spawns a native subprocess to execute the Lean 4 compiler on the host OS.
        Uses `lake env lean` to resolve Mathlib dependencies.
        Timeout set to 120s to accommodate Mathlib elaboration passes.
        """
        try:
            result = subprocess.run(
                ["lake", "env", "lean", os.path.basename(file_path)], 
                capture_output=True, 
                text=True, 
                timeout=120,
                cwd=self.proofs_dir
            )
            
            # Primary check: Lean's own sorry detection is authoritative
            # The compiler emits "declaration uses 'sorry'" as a warning
            lean_sorry_warning = "declaration uses" in result.stderr and "sorry" in result.stderr
            
            # Secondary check: read the file for sorry as a tactic keyword
            has_sorry_in_code = False
            with open(file_path, "r") as f:
                final_content = f.read()
            in_block_comment = False
            for line in final_content.split("\n"):
                stripped = line.strip()
                if "/-" in stripped:
                    in_block_comment = True
                if "-/" in stripped:
                    in_block_comment = False
                    continue
                if in_block_comment or stripped.startswith("--"):
                    continue
                if "sorry" in stripped:
                    has_sorry_in_code = True
                    break
            
            has_sorry = lean_sorry_warning or has_sorry_in_code
            
            if result.returncode == 0 and not has_sorry:
                return {
                    "status": "VERIFIED", 
                    "message": "Riemann Hypothesis Geometry Graph Compiled Perfectly!",
                    "output": result.stdout
                }
            else:
                error_text = (result.stderr + "\n" + result.stdout).strip()
                if has_sorry and result.returncode == 0:
                    error_text = "Proof still contains 'sorry' — the AI did not replace the placeholder."
                return {
                    "status": "FAILED", 
                    "message": "Compiler Rejected Logical Tactic Synthesis.",
                    "error": error_text if error_text else "Unknown compilation failure (empty output)."
                }
        except FileNotFoundError:
            return {
                "status": "SYSTEM_UNAVAILABLE", 
                "message": "Lean 4 compiler not found. Run: curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh"
            }
        except subprocess.TimeoutExpired:
            return {
                "status": "TIMEOUT", 
                "message": "Lean 4 timed out after 120s. The proof may be valid but computationally expensive."
            }
